onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /TI60F225_MIPI_dsi_tb/i_pclk
add wave -noupdate /TI60F225_MIPI_dsi_tb/o_pclk
add wave -noupdate /TI60F225_MIPI_dsi_tb/i_sys_clk
add wave -noupdate /TI60F225_MIPI_dsi_tb/mipi_clk
add wave -noupdate /TI60F225_MIPI_dsi_tb/i_mipi_tx_pclk
add wave -noupdate /TI60F225_MIPI_dsi_tb/i_arstn
add wave -noupdate /TI60F225_MIPI_dsi_tb/i_arstn_dsi_ctrl
add wave -noupdate /TI60F225_MIPI_dsi_tb/i_tx_arstn
add wave -noupdate /TI60F225_MIPI_dsi_tb/r_rstn_cmd
add wave -noupdate /TI60F225_MIPI_dsi_tb/video_x
add wave -noupdate /TI60F225_MIPI_dsi_tb/video_y
add wave -noupdate /TI60F225_MIPI_dsi_tb/video_valid
add wave -noupdate /TI60F225_MIPI_dsi_tb/video_de
add wave -noupdate /TI60F225_MIPI_dsi_tb/video_hs
add wave -noupdate /TI60F225_MIPI_dsi_tb/video_vs
add wave -noupdate /TI60F225_MIPI_dsi_tb/out_x
add wave -noupdate /TI60F225_MIPI_dsi_tb/out_y
add wave -noupdate /TI60F225_MIPI_dsi_tb/out_valid
add wave -noupdate /TI60F225_MIPI_dsi_tb/out_de
add wave -noupdate /TI60F225_MIPI_dsi_tb/out_hs
add wave -noupdate /TI60F225_MIPI_dsi_tb/out_vs
add wave -noupdate /TI60F225_MIPI_dsi_tb/w_axi_rdata
add wave -noupdate /TI60F225_MIPI_dsi_tb/w_axi_awready
add wave -noupdate /TI60F225_MIPI_dsi_tb/w_axi_wready
add wave -noupdate /TI60F225_MIPI_dsi_tb/w_axi_arready
add wave -noupdate /TI60F225_MIPI_dsi_tb/w_axi_rvalid
add wave -noupdate /TI60F225_MIPI_dsi_tb/w_axi_bvalid
add wave -noupdate /TI60F225_MIPI_dsi_tb/w_axi_awaddr
add wave -noupdate /TI60F225_MIPI_dsi_tb/w_axi_awvalid
add wave -noupdate /TI60F225_MIPI_dsi_tb/w_axi_wdata
add wave -noupdate /TI60F225_MIPI_dsi_tb/w_axi_wvalid
add wave -noupdate /TI60F225_MIPI_dsi_tb/w_axi_bready
add wave -noupdate /TI60F225_MIPI_dsi_tb/w_axi_araddr
add wave -noupdate /TI60F225_MIPI_dsi_tb/w_axi_arvalid
add wave -noupdate /TI60F225_MIPI_dsi_tb/w_axi_rready
add wave -noupdate /TI60F225_MIPI_dsi_tb/w_axi_awaddr_0
add wave -noupdate /TI60F225_MIPI_dsi_tb/w_axi_awvalid_0
add wave -noupdate /TI60F225_MIPI_dsi_tb/w_axi_wdata_0
add wave -noupdate /TI60F225_MIPI_dsi_tb/w_axi_wvalid_0
add wave -noupdate /TI60F225_MIPI_dsi_tb/w_axi_bready_0
add wave -noupdate /TI60F225_MIPI_dsi_tb/w_axi_araddr_0
add wave -noupdate /TI60F225_MIPI_dsi_tb/w_axi_arvalid_0
add wave -noupdate /TI60F225_MIPI_dsi_tb/w_axi_rready_0
add wave -noupdate /TI60F225_MIPI_dsi_tb/w_state
add wave -noupdate /TI60F225_MIPI_dsi_tb/w_confdone
add wave -noupdate /TI60F225_MIPI_dsi_tb/mipi_tx0_clk_LP_P_OUT
add wave -noupdate /TI60F225_MIPI_dsi_tb/mipi_tx0_clk_LP_N_OUT
add wave -noupdate /TI60F225_MIPI_dsi_tb/mipi_tx0_clk_HS_OE
add wave -noupdate /TI60F225_MIPI_dsi_tb/mipi_tx0_data3_LP_P_OUT
add wave -noupdate /TI60F225_MIPI_dsi_tb/mipi_tx0_data2_LP_P_OUT
add wave -noupdate /TI60F225_MIPI_dsi_tb/mipi_tx0_data1_LP_P_OUT
add wave -noupdate /TI60F225_MIPI_dsi_tb/mipi_tx0_data0_LP_P_OUT
add wave -noupdate /TI60F225_MIPI_dsi_tb/mipi_tx0_data0_LP_N_OUT
add wave -noupdate /TI60F225_MIPI_dsi_tb/mipi_tx0_data3_LP_N_OUT
add wave -noupdate /TI60F225_MIPI_dsi_tb/mipi_tx0_data2_LP_N_OUT
add wave -noupdate /TI60F225_MIPI_dsi_tb/mipi_tx0_data1_LP_N_OUT
add wave -noupdate /TI60F225_MIPI_dsi_tb/mipi_tx0_data0_HS_OUT
add wave -noupdate /TI60F225_MIPI_dsi_tb/mipi_tx0_data1_HS_OUT
add wave -noupdate /TI60F225_MIPI_dsi_tb/mipi_tx0_data2_HS_OUT
add wave -noupdate /TI60F225_MIPI_dsi_tb/mipi_tx0_data3_HS_OUT
add wave -noupdate /TI60F225_MIPI_dsi_tb/mipi_tx0_data3_HS_OE
add wave -noupdate /TI60F225_MIPI_dsi_tb/mipi_tx0_data2_HS_OE
add wave -noupdate /TI60F225_MIPI_dsi_tb/mipi_tx0_data1_HS_OE
add wave -noupdate /TI60F225_MIPI_dsi_tb/mipi_tx0_data0_HS_OE
add wave -noupdate /TI60F225_MIPI_dsi_tb/mipi_tx0_data0_LP_P_IN
add wave -noupdate /TI60F225_MIPI_dsi_tb/mipi_tx0_data0_LP_N_IN
add wave -noupdate /TI60F225_MIPI_dsi_tb/r_rstn_video
add wave -noupdate /TI60F225_MIPI_dsi_tb/r_pack_hs_1P
add wave -noupdate /TI60F225_MIPI_dsi_tb/r_hs_cnt
add wave -noupdate /TI60F225_MIPI_dsi_tb/r_frame_cnt
add wave -noupdate /TI60F225_MIPI_dsi_tb/r_syncbyte_cnt
add wave -noupdate /TI60F225_MIPI_dsi_tb/mipi_tx0_data0_HS_OE_1P
add wave -noupdate /TI60F225_MIPI_dsi_tb/r_axi_rdata
add wave -noupdate /TI60F225_MIPI_dsi_tb/r_axi_awready
add wave -noupdate /TI60F225_MIPI_dsi_tb/r_axi_wready
add wave -noupdate /TI60F225_MIPI_dsi_tb/r_axi_arready
add wave -noupdate /TI60F225_MIPI_dsi_tb/r_axi_rvalid
add wave -noupdate /TI60F225_MIPI_dsi_tb/r_axi_bvalid
add wave -noupdate /TI60F225_MIPI_dsi_tb/mipi_tx0_data3_LP_P_OE
add wave -noupdate /TI60F225_MIPI_dsi_tb/mipi_tx0_data2_LP_P_OE
add wave -noupdate /TI60F225_MIPI_dsi_tb/mipi_tx0_data1_LP_P_OE
add wave -noupdate /TI60F225_MIPI_dsi_tb/mipi_tx0_data0_LP_P_OE
add wave -noupdate /TI60F225_MIPI_dsi_tb/mipi_tx0_data3_LP_N_OE
add wave -noupdate /TI60F225_MIPI_dsi_tb/mipi_tx0_data2_LP_N_OE
add wave -noupdate /TI60F225_MIPI_dsi_tb/mipi_tx0_data1_LP_N_OE
add wave -noupdate /TI60F225_MIPI_dsi_tb/mipi_tx0_data0_LP_N_OE
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {0 ps} 0}
quietly wave cursor active 0
configure wave -namecolwidth 236
configure wave -valuecolwidth 85
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits us
update
WaveRestoreZoom {80441335 ps} {211902499 ps}
